# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 王捉虾的Homepage
# brief-intro: Developer

# the subpath of your site, e.g. /blog
baseurl: "" 
# the base hostname & protocol for your site
url: "http://liinnux.github.io" 

permalink: /:year/:month/:day/:title/

# other links
github_username:  liinnux
email: liinux@qq.com
# weibo_username: @test
# linkedin_username: test

description_footer: 王捉虾的博客

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: liinnux
duoshuo_url: "http://liinnux.github.io"
#disqus_shortname: liinnux

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 01ead8d132fad393952a3d004d92453e
# google 分析追踪id
google_analytics_id: UA-77782495-1


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5

# bundle 
exclude: ["vendor"]
